YeniYilKarti/Controllers/KartController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YeniYilKarti.Models;

namespace YeniYilKarti.Controllers
{

    public class KartController : BaseController
    {
        [Authorize]
        public ActionResult Index()
        {
            string id = User.Identity.GetUserId();
            List<Kart> kartlar = db.Kartlar.Where(x => x.UserId == id).ToList();
            return View(kartlar);
        }
        [Authorize]
        public ActionResult Yeni()
        {
            //https://stackoverflow.com/questions/15989764/display-all-images-in-a-folder-in-mvc-with-a-foreach
            ViewBag.Images = Directory.EnumerateFiles(Server.MapPath("~/Img")).Select(fn => "~/Img/" + Path.GetFileName(fn));
            return View();
        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Yeni(KartVM vm)
        {
            string id = User.Identity.GetUserId();
            ViewBag.Images = Directory.EnumerateFiles(Server.MapPath("~/Img")).Select(fn => "~/Img/" + Path.GetFileName(fn));
            if (ModelState.IsValid)
            {
                var bolum = vm.Mesaj.Length / 3;
                var aralik = bolum * 2;
                string Mesaj1 = vm.Mesaj.Substring(0, bolum);
                string Mesaj2 = vm.Mesaj.Substring(bolum, bolum);
                string Mesaj3 = vm.Mesaj.Substring(aralik);
                Kart kart = new Kart()
                {
                    AliciAd = vm.AliciAd,
                    GonderenAd = vm.GonderenAd,
                    ResimYolu = vm.Resimyolu,
                    Mesaj1 = Mesaj1,
                    Mesaj2 = Mesaj2,
                    Mesaj3 = Mesaj3,
                    UserId = id,
                    Baslik = "Sevgili " + vm.AliciAd
                };
                db.Kartlar.Add(kart);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(vm);
        }
        [Authorize]
        public ActionResult Sil(int id)
        {
            Kart kart = db.Kartlar.Find(id);
            if (kart == null)
            {
                return HttpNotFound();
            }
            db.Kartlar.Remove(kart);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Indir(int id)
        {
            Kart kart = db.Kartlar.Find(id);
            if (kart == null)
            {
                return HttpNotFound();
            }
            return View(kart);
        }
    }
}

YeniYilKarti/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Yeni Yıl Kart Uygulaması</title>
    <link rel="icon" href="~/icons8_santas_hat.ico" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("css", false)

</head>
<body>
    <nav class="p-3 pl-5 pr-5 navbar navbar-expand-lg navbar-light bg-transparent">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index","Home")">
                        <i class="fas fa-home"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index","Kart")">
                        <i class="fas fa-gift"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Contact","Home")">
                        <i class="fas fa-file-signature"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <audio id="track">
                        <source src="~/Img/We%20Wish%20You%20a%20Merry%20Christmas%20with%20Lyrics%20Christmas%20Carol%20%20Song%20Kids%20Love%20to%20Sing.mp3"  type="audio/mpeg" />
                    </audio>
                    <div id="player-container">
                        <div id="play-pause" class="nav-link play">Play</div>
                    </div>
                </li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </nav>
    <div class="container-fluid body-content">
        @RenderBody()
    </div>
    <footer class="fixed-bottom text-center" style="z-index:-1;">
        <p>&copy; @DateTime.Now.Year - Yeni Yıl Kartı Uygulaması</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dom-to-image/2.6.0/dom-to-image.min.js" integrity="sha512-01CJ9/g7e8cUmY0DFTMcUw/ikS799FHiOA0eyHsUWfOetgbx/t6oV4otQ5zXKQyIrQGTHSmRVPIgrgLcZi/WMA==" crossorigin="anonymous"></script>
    @RenderSection("scripts", required: false)
    <script>
        var track = document.getElementById('track');

        var controlBtn = document.getElementById('play-pause');

        function playPause() {
            if (track.paused) {
                track.play();
                controlBtn.textContent = "Pause";
            } else {
                track.pause();
                controlBtn.textContent = "Play";
            }
        }

        controlBtn.addEventListener("click", playPause);
        track.addEventListener("ended", function () {
            controlBtn.className = "play";
        });

    </script>
</body>
</html>